#!/bin/bash


#####################
# Author : Harshath
# Date : 29th-April
#
# Version : v1
#
# This script will report the AWS resource usage
#####################


# AWS S3
# AWS EC2
# AWS Lambda
# AWS IAM Users

# list s3 buckets
echo "Print list of s3 buckets"
aws s3 ls > resourceTracker

#list EC2 Instance
echo "Print list of ec2 buckets"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'

# list lambda
echo "Print list of lambda fuctions"
aws lambda list-functions >> resourceTracker

# list IAM users
echo "print list of IAM Users"
aws iam list-users


~

